### ISSUE TITLE
Grails 2.0.0-console errors

### ISSUE THREAD

**Issue by bronoman** [joergrech/KickstartWithBootstrap#1]
# Environment

Win7 Home Premium
jdk1.7.0_01
Grails 2.0.0
# Symptoms

When starting a new application (here called: bootstripper) and installing the KickstartWithBootstrap Plugin, the following errors are shown when pulling up the homepage of the application:
# Console Output

'''
E:\Grails\workspace\bootstripper>grails run-app
| Server running. Browse to http://localhost:8080/bootstripper
home.index: [controller:home, action:index]
| Error 2012-02-09 22:37:48,490 ["http-bio-8080"-exec-1] ERROR resource.ResourceMeta  - Resource not found: /bootstrap/js/bootstrap-transition.js
| Error 2012-02-09 22:37:49,702 ["http-bio-8080"-exec-1] ERROR [/bootstripper].[gsp]  - Servlet.service() for servlet [gsp] in context with path [/boo
tstripper] threw exception
Message: It looks like you are missing some calls to the r:layoutResources tag. After rendering your page the following have not been rendered: [defer
]
    Line | Method
->> 1110 | runWorker in java.util.concurrent.ThreadPoolExecutor

---

|    603 | run       in java.util.concurrent.ThreadPoolExecutor$Worker
^    722 | run . . . in java.lang.Thread
'''
# Stacktrace:

'''
2012-02-09 22:37:49,709 ["http-bio-8080"-exec-1] ERROR StackTrace  - Full Stack Trace:
java.lang.RuntimeException: It looks like you are missing some calls to the r:layoutResources tag. After rendering your page the following have not been rendered: [defer]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
    at com.springsource.loaded.ri.ReflectiveInterceptor.jlrConstructorNewInstance(ReflectiveInterceptor.java:963)
    at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
    at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:54)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:190)
    at org.grails.plugin.resource.DevModeSanityFilter.doFilter(DevModeSanityFilter.groovy:52)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.codehaus.groovy.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:69)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.codehaus.groovy.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:69)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
    at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
    at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:259)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:240)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:164)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:462)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:164)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:403)
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:301)
    at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:162)
    at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:140)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:309)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:722)
2012-02-09 22:37:49,713 ["http-bio-8080"-exec-1] ERROR StackTrace  - Full Stack Trace:
java.lang.RuntimeException: It looks like you are missing some calls to the r:layoutResources tag. After rendering your page the following have not been rendered: [defer]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:722)
'''
# Fixes / Workarounds found

The first error can be fixed by copying bootstrap-transition.js found at 
https://github.com/twitter/bootstrap/blob/master/js/bootstrap-transition.js

**Comment by joergrech** [comment]
Hi Bronoman,
  thank you for the error message. The problem was that I referenced an unnecessary script (bootstrap-transition.js is included in bootstrap.js) and did not use the resource plugin (required in Grails 2.0.0). The problem should now be gone. I tested the plugin on a new Grails 2.0.0 and 1.3.7 project.

Bye,
Joerg

**Comment by bronoman** [comment]
Thank you very much. 
As a sign of my appreciation, I have added a few screenshots here to support the marketing efforts: http://grails.org/plugin/kickstart-with-bootstrap > tab: screenshots
best of greetings - ins kalte Deutschland - 
from sunny Singapore!

**Comment by joergrech** [comment]
Hi Bronoman,
  yes I saw that you added the screenshot - thank you very much. And also
for the error detection and feedback on Github! My plan is to integrate the
bootstrap plugin and a REST plugin in the next versions - or to reintegrate
the jQuery Mobile scaffolding I've currently removed for simplicity. If you
have some feedback or whishes let me know.

Best regards from snowy Karlsruhe,
Joerg

On Tue, Feb 14, 2012 at 17:04, bronoman <
reply@reply.github.com

> wrote:
> 
> Thank you very much.
> As a sign of my appreciation, I have added a few screenshots here to
> support the marketing efforts:
> http://grails.org/plugin/kickstart-with-bootstrap > tab: screenshots
> best of greetings - ins kalte Deutschland -
> from sunny Singapore!
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/joergrech/KickstartWithBootstrap/issues/1#issuecomment-3963769

## 

_Dr. Jrg Rech_
Kriegsstr. 164
76133 Karlsruhe, Germany

E-Mail:  joerg.rech@gmail.com
Twitter:  http://twitter.com/joergrech
Web:  http://www.joerg-rech.com
Xing: http://www.xing.com/profile/Joerg_Rech/
LinkedIn: http://www.linkedin.com/in/joergrech

**Comment by bronoman** [comment]
To tell you the truth, I'm a big fan of scaffolding. I have not looked at jQuery Mobile, but I could for sure imagine to expand the scaffolding idea from CRUD to CRUSHEDIT where the new characters S,H,E,I and T stand for:
S = Search (Fulltext and AND Search on all fields of a domain class)
H = History (of changes)
E = Enhanced Edit (Excel/Table style, like Sharepoint tables)
I = Information or help on field level (toggle button to add Info icons to all fields which the lead to gdocs)
T = Template for data reuse (an existing record can be promoted to template status and copied)
Just my 50 cents :)
P.S.: I'm still looking for a feature that starts with G, so it would be GSCHEID!
Herzliche Grüße aus dem 29 Grad warmen Singapur! Tolle Arbeit, echt.

**Comment by starryknight64** [comment]
Running Grails 2.2 and getting this same error.
I'm wanting to copy the bootstrap-transition.js file to see if that works, but I'm not sure where to copy it to?

**Comment by joergrech** [comment]
Can you check if your app has imported the lesscss-resource plugin? It should be inherited from the Kickstart plugin but sometimes it seems not to do so (since Grails 2.2). You can try to clean & compile your app and try again or install the plugin into your BuildConfig.groovy directly:

compile ":lesscss-resources:1.3.1"

If you just want to work with the less files: they are copied into your app under /web-app/less after executing the "grails kickstart" script.

If this doesn't help I need more info such as Kickstart version, stacktraces, etc.

**Comment by starryknight64** [comment]
Nevermind, figured it out. I have heavily modified my auth.gsp (originally generated from running Spring Security's s2-quickstart command) which is what was causing this error. Thanks for looking into it! Much appreciated. :)
