### ISSUE TITLE
0.8.6 i18n not found

### ISSUE THREAD

**Issue by gonzalogarciajaubert** [joergrech/KickstartWithBootstrap#21]
When deploy it in tomcat 6 and 7, the next error arise:

caused by: java.io.FileNotFoundException: /Users/sfhynx/Desarrollo/apache-tomcat-6.0.35/bin/./grails-app/i18n
    at org.codehaus.groovy.runtime.DefaultGroovyMethods.checkDir(DefaultGroovyMethods.java:15537)
    at org.codehaus.groovy.runtime.DefaultGroovyMethods.eachFileRecurse(DefaultGroovyMethods.java:15616)
    at org.codehaus.groovy.runtime.DefaultGroovyMethods.eachFileRecurse(DefaultGroovyMethods.java:15855)
    at org.codehaus.groovy.runtime.dgm$179.invoke(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:271)
    at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
    at KickstartWithBootstrapGrailsPlugin$_closure1.doCall(KickstartWithBootstrapGrailsPlugin.groovy:48)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    ... 37 more

I thing the problem is in./KickstartWithBootstrapGrailsPlugin.groovy: new File("./grails-app/i18n").eachFileRecurse

Edit: if you comment the "doWithApplicationContext" it works.

**Comment by joergrech** [comment]
Hi,
  thanks for the tipp. The code is used to retrieve all I18 files and
prepare a list for the language selector. I will look into how I can get
these files in an OS-neutral way. It works on Windows using GGTS/eclipse
but from the path you stated I assume that you run your tomcat on Windows -
or Mac/Unix?

Joerg

On Mon, Nov 12, 2012 at 10:19 AM, Gonzalo Garcia Jaubert <
notifications@github.com> wrote:

> When deploy to tomcat the next error raise:
> 
> caused by: java.io.FileNotFoundException:
> /Users/sfhynx/Desarrollo/apache-tomcat-6.0.35/bin/./grails-app/i18n
> at
> org.codehaus.groovy.runtime.DefaultGroovyMethods.checkDir(DefaultGroovyMethods.java:15537)
> at
> org.codehaus.groovy.runtime.DefaultGroovyMethods.eachFileRecurse(DefaultGroovyMethods.java:15616)
> at
> org.codehaus.groovy.runtime.DefaultGroovyMethods.eachFileRecurse(DefaultGroovyMethods.java:15855)
> at org.codehaus.groovy.runtime.dgm$179.invoke(Unknown Source)
> at
> org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:271)
> at
> org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
> at
> org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
> at
> org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
> at
> org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
> at
> KickstartWithBootstrapGrailsPlugin$_closure1.doCall(KickstartWithBootstrapGrailsPlugin.groovy:48)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at
> sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
> at
> sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
> at java.lang.reflect.Method.invoke(Method.java:597)
> at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
> ... 37 more
> 
> i thing the problem is in./KickstartWithBootstrapGrailsPlugin.groovy: new
> File("./grails-app/i18n").eachFileRecurse
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/joergrech/KickstartWithBootstrap/issues/21.

## 

_Dr. Jörg Rech_
Freelancer
Grails | Java | jQuery | iOS | Android
Kriegsstr. 164
76133 Karlsruhe, Germany

Twitter:  http://twitter.com/joergrech
Web:  http://www.joerg-rech.com
Xing: http://www.xing.com/profile/Joerg_Rech/
LinkedIn: http://www.linkedin.com/in/joergrech

**Comment by gonzalogarciajaubert** [comment]
Hi @joergrech ,

  I'm working with STS in Windows and it runs ok, but when i deploy it in tomcat the error is that "./" is the root of tomcat, and not the root of the app.

Regards,
Gonzalo

Edit: Tomcat 6/7 Windows

**Comment by joergrech** [comment]
Hi, thanks for the fix. I integrated a similar approach in version 0.8.8.

**Comment by gonzalogarciajaubert** [comment]
Sorry, duplicate issue

**Comment by jeltok** [comment]
Tested version 0.8.9 in JBoss 7.1.1 and it works well. Version 0.8.6 was failing with grails-app/i18n FileNotFoundException
