### ISSUE TITLE
Grails 2.2 compatibility?

### ISSUE THREAD

**Issue by kastork** [joergrech/KickstartWithBootstrap#27]
Should the plugin be expected to work with Grails 2.2 yet?

**Comment by joergrech** [comment]
Thanks for the tip. It looks like the dependency management of Grails 2.2 changed and causes problems. If kickstart is installed the project will not inherit the plugins the kickstart plugin used.

A preliminary fix is to add the following lines to the BuildConfig.groovy file within the project's conf directory:

> ```
>   compile ":kickstart-with-bootstrap:0.8.9"
>   runtime ":jquery:1.8.3"
>   compile ":lesscss-resources:1.3.0.3"
> ```

(adding them via "grails install-plugin ..." should work also).

This fix will result in a working system but I got some informative logs via the errors channel (red) from org.apache.coyote and org.apache.catalina (Tomcat) that are new to me. 

Furthermore Grails 2.2 introduced a messages_nb.properties file for the Locale "nb" that is not standard (at least according to ISO 3166 - see http://en.wikipedia.org/wiki/ISO_3166-1) and, therefore, has no flag icon and will result in errors about a missing resource file "nb.png". If this is meant for Norway the locale should be "no". 

> A quick fix is to a) delete the property file, b) rename the file to "messages_no.properties", or copy the flag image file "no.png" to "nb.png" within web-app/images/flags folder of the kickstart plugin.

**Comment by kastork** [comment]
I'd come to those workarounds as well, except I haven't yet found a specific need to grab the older jquery plugin (default for grails 2.2 is jquery plugin 1.8.3)

Do you believe the modified scaffolding templates are reliable for 2.2?

**Comment by joergrech** [comment]
Yes loading jQuery 1.8.3 should be fine as well. (I corrected the previous comment)

Regarding the scaffolding: the Docs (http://grails.org/doc/2.2.0/guide/introduction.html#whatsNew22) do not mention changes. Did you have problems with the scaffolding?

**Comment by kastork** [comment]
No... just didn't want to start trying if things were known not to work.

**Comment by joergrech** [comment]
Assumed fixed

**Comment by sdidit** [comment]
I have tested with Grails 2.2 and the only thing not working was the retrieval of the Groovy version in systeminfo.gsp. I simply changed it to GroovySystem.getVersion().

**Comment by DramaDesu** [comment]
I got exeception too.

Error 500 - Internal Server Error.
Error evaluating expression [request.'javax.servlet.error.message'?.indexOf(':') == null ? request.'javax.servlet.error.message'?.encodeAsHTML() : request.'javax.servlet.error.message'?.substring(0, request.'javax.servlet.error.message'?.indexOf(':')).encodeAsHTML()] on line [11]: String index out of range: -1

My BuildConfig.groovy:
    plugins {
        runtime ":hibernate:$grailsVersion"
        compile ':kickstart-with-bootstrap:0.8.9'
        runtime ":jquery:1.8.3"
        runtime ":resources:1.1.6"
        //compile ':lesscss-resources:1.3.1'
        runtime ':lesscss-resources:1.3.1'

```
    // Uncomment these (or add new ones) to enable additional resources capabilities
    //runtime ":zipped-resources:1.0"
    //runtime ":cached-resources:1.0"
    //runtime ":yui-minify-resources:0.1.4"

    build ":tomcat:$grailsVersion"

    runtime ":database-migration:1.2.1"

    compile ':cache:1.0.1'
}
```

So I have the flag.

So When I tried to create a new demo page, I got exeception:

Error processing GroovyPageView create.gsp at line 464
Error Details
Error 500   Error processing GroovyPageView: Error executing tag <g:form>: Error executing tag <g:render>: Error evaluating expression [kickstartwithbootstrapgrailsplugin._DemoPage$Suit?.values()] on line [136]: java.lang.VerifyError: (class: kickstartwithbootstrapgrailsplugin/_DemoPage$Suit, method: instanceOf signature: (Ljava/lang/Class;)Z) Incompatible object argument for function call
Servlet     grails
URI     /Magic/grails/_DemoPage/create.dispatch
Exception Message:  (class: kickstartwithbootstrapgrailsplugin/_DemoPage$Suit, method: instanceOf signature: (Ljava/lang/Class;)Z) Incompatible object argument for function call
Caused by:  Error processing GroovyPageView: Error executing tag <g:form>: Error executing tag <g:render>: Error evaluating expression [kickstartwithbootstrapgrailsplugin._DemoPage$Suit?.values()] on line [136]: java.lang.VerifyError: (class: kickstartwithbootstrapgrailsplugin/_DemoPage$Suit, method: instanceOf signature: (Ljava/lang/Class;)Z) Incompatible object argument for function call
Class:  create.gsp
At Line:    [464]
Code Snippet:   

Stack Trace

org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error processing GroovyPageView: Error executing tag <g:form>: Error executing tag <g:render>: Error evaluating expression [kickstartwithbootstrapgrailsplugin._DemoPage$Suit?.values()] on line [136]: java.lang.VerifyError: (class: kickstartwithbootstrapgrailsplugin/_DemoPage$Suit, method: instanceOf signature: (Ljava/lang/Class;)Z) Incompatible object argument for function call

```
at org.codehaus.groovy.grails.web.servlet.view.GroovyPageView.createGroovyPageException(GroovyPageView.java:205)

at org.codehaus.groovy.grails.web.servlet.view.GroovyPageView.handleException(GroovyPageView.java:181)

at org.codehaus.groovy.grails.web.servlet.view.GroovyPageView.renderWithTemplateEngine(GroovyPageView.java:152)

at org.codehaus.groovy.grails.web.servlet.view.GroovyPageView.renderMergedOutputModel(GroovyPageView.java:83)

at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:262)

at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1180)

at org.codehaus.groovy.grails.web.servlet.GrailsDispatcherServlet.doDispatch(GrailsDispatcherServlet.java:369)

at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:852)

at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:882)

at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:778)

at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)

at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)

at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)

at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)

at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:195)

at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)

at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)

at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:259)

at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)

at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)

at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:70)

at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)

at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)

at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:70)

at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)

at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)

at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:70)

at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)

at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)

at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:749)

at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:487)

at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:412)

at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:339)

at org.codehaus.groovy.grails.web.util.WebUtils.forwardRequestForUrlMappingInfo(WebUtils.java:314)

at org.codehaus.groovy.grails.web.util.WebUtils.forwardRequestForUrlMappingInfo(WebUtils.java:279)

at org.codehaus.groovy.grails.web.util.WebUtils.forwardRequestForUrlMappingInfo(WebUtils.java:270)

at org.codehaus.groovy.grails.web.mapping.filter.UrlMappingsFilter.doFilterInternal(UrlMappingsFilter.java:221)

at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)

at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)

at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)

at org.codehaus.groovy.grails.web.sitemesh.GrailsPageFilter.obtainContent(GrailsPageFilter.java:200)

at org.codehaus.groovy.grails.web.sitemesh.GrailsPageFilter.doFilter(GrailsPageFilter.java:151)

at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)

at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)

at javax.servlet.FilterChain$doFilter.call(Unknown Source)

at org.grails.plugin.resource.DevModeSanityFilter.doFilter(DevModeSanityFilter.groovy:44)

at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)

at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)

at org.codehaus.groovy.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:69)

at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)

at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)

at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)

at org.codehaus.groovy.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:66)

at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)

at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)

at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)

at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)

at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)

at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)

at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:259)

at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)

at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)

at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)

at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)

at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)

at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)

at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)

at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)

at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1002)

at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:585)

at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312)

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)

at java.lang.Thread.run(Thread.java:722)
```

Caused by: org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: Error executing tag <g:form>: Error executing tag <g:render>: Error evaluating expression [kickstartwithbootstrapgrailsplugin._DemoPage$Suit?.values()] on line [136]: java.lang.VerifyError: (class: kickstartwithbootstrapgrailsplugin/_DemoPage$Suit, method: instanceOf signature: (Ljava/lang/Class;)Z) Incompatible object argument for function call

```
at org.codehaus.groovy.grails.web.pages.GroovyPage.throwRootCause(GroovyPage.java:464)

at org.codehaus.groovy.grails.web.pages.GroovyPage.invokeTag(GroovyPage.java:452)

at sun.reflect.GeneratedMethodAccessor292.invoke(Unknown Source)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:601)

at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)

at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)

at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1076)

at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)

at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:906)

at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:980)

at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)

at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:906)

at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:66)

at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)

at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)

at F__Develop_Grails_Magic_grails_app_views__DemoPage_create_gsp$_run_closure2.doCall(create.gsp:30)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:601)

at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)

at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)

at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1076)

at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)

at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:906)

at groovy.lang.Closure.call(Closure.java:415)

at groovy.lang.Closure.call(Closure.java:409)

at org.codehaus.groovy.grails.web.taglib.GroovyPageTagBody.executeClosure(GroovyPageTagBody.java:205)

at org.codehaus.groovy.grails.web.taglib.GroovyPageTagBody.captureClosureOutput(GroovyPageTagBody.java:107)

at org.codehaus.groovy.grails.web.taglib.GroovyPageTagBody.call(GroovyPageTagBody.java:218)

at java_util_concurrent_Callable$call.call(Unknown Source)

at org.codehaus.groovy.grails.plugins.web.taglib.SitemeshTagLib.captureTagContent(SitemeshTagLib.groovy:41)

at org.codehaus.groovy.grails.plugins.web.taglib.SitemeshTagLib.captureTagContent(SitemeshTagLib.groovy)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:601)

at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)

at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)

at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1076)

at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)

at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:906)

at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1021)

at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)

at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:906)

at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:66)

at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:153)

at org.codehaus.groovy.grails.plugins.web.taglib.SitemeshTagLib$_closure3.doCall(SitemeshTagLib.groovy:142)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:601)

at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)

at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)

at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1076)

at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)

at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:906)

at groovy.lang.Closure.call(Closure.java:415)

at org.codehaus.groovy.grails.web.pages.GroovyPage.invokeTag(GroovyPage.java:399)

at org.codehaus.groovy.grails.web.pages.GroovyPage$invokeTag.callCurrent(Unknown Source)

at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)

at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)

at F__Develop_Grails_Magic_grails_app_views__DemoPage_create_gsp.run(create.gsp:34)

at org.codehaus.groovy.grails.web.pages.GroovyPageWritable.writeTo(GroovyPageWritable.java:218)

at org.codehaus.groovy.grails.web.servlet.view.GroovyPageView.renderWithTemplateEngine(GroovyPageView.java:148)

... 71 more
```

Caused by: org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: Error executing tag <g:render>: Error evaluating expression [kickstartwithbootstrapgrailsplugin._DemoPage$Suit?.values()] on line [136]: java.lang.VerifyError: (class: kickstartwithbootstrapgrailsplugin/_DemoPage$Suit, method: instanceOf signature: (Ljava/lang/Class;)Z) Incompatible object argument for function call

```
at org.codehaus.groovy.grails.web.pages.GroovyPage.throwRootCause(GroovyPage.java:464)

at org.codehaus.groovy.grails.web.pages.GroovyPage.invokeTag(GroovyPage.java:452)

at sun.reflect.GeneratedMethodAccessor292.invoke(Unknown Source)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:601)

at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)

at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)

at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1076)

at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)

at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:906)

at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:980)

at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)

at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:906)

at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:66)

at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)

at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)

at F__Develop_Grails_Magic_grails_app_views__DemoPage_create_gsp$_run_closure2_closure17.doCall(create.gsp:24)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:601)

at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)

at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)

at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1076)

at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)

at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:906)

at groovy.lang.Closure.call(Closure.java:415)

at groovy.lang.Closure.call(Closure.java:409)

at org.codehaus.groovy.grails.web.taglib.GroovyPageTagBody.executeClosure(GroovyPageTagBody.java:205)

at org.codehaus.groovy.grails.web.taglib.GroovyPageTagBody.captureClosureOutput(GroovyPageTagBody.java:107)

at org.codehaus.groovy.grails.web.taglib.GroovyPageTagBody.call(GroovyPageTagBody.java:218)

at java_util_concurrent_Callable$call.call(Unknown Source)

at org.codehaus.groovy.grails.plugins.web.taglib.FormTagLib$_closure9.doCall(FormTagLib.groovy:373)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:601)

at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)

at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)

at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1076)

at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)

at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:906)

at groovy.lang.Closure.call(Closure.java:415)

at org.codehaus.groovy.grails.web.pages.GroovyPage.invokeTag(GroovyPage.java:399)

... 135 more
```

Caused by: org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error evaluating expression [kickstartwithbootstrapgrailsplugin._DemoPage$Suit?.values()] on line [136]: java.lang.VerifyError: (class: kickstartwithbootstrapgrailsplugin/_DemoPage$Suit, method: instanceOf signature: (Ljava/lang/Class;)Z) Incompatible object argument for function call

```
at org.codehaus.groovy.grails.web.pages.GroovyPage.evaluate(GroovyPage.java:285)

at org.codehaus.groovy.grails.web.pages.GroovyPage$evaluate.callCurrent(Unknown Source)

at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)

at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)

at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:153)

at F__Develop_Grails_Magic_grails_app_views__DemoPage__form_gsp.run(_form.gsp:136)

at org.codehaus.groovy.grails.web.pages.GroovyPageWritable.writeTo(GroovyPageWritable.java:218)

at org.codehaus.groovy.grails.web.pages.GroovyPagesTemplateRenderer.makeTemplate(GroovyPagesTemplateRenderer.java:182)

at org.codehaus.groovy.grails.web.pages.GroovyPagesTemplateRenderer.render(GroovyPagesTemplateRenderer.java:83)

at org.codehaus.groovy.grails.web.pages.GroovyPagesTemplateRenderer$render.call(Unknown Source)

at org.codehaus.groovy.grails.plugins.web.taglib.RenderTagLib$_closure10.doCall(RenderTagLib.groovy:580)

at sun.reflect.GeneratedMethodAccessor363.invoke(Unknown Source)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:601)

at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)

at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)

at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1076)

at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)

at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:906)

at groovy.lang.Closure.call(Closure.java:415)

at org.codehaus.groovy.grails.web.pages.GroovyPage.invokeTag(GroovyPage.java:399)

... 177 more
```

Caused by: org.codehaus.groovy.runtime.InvokerInvocationException: java.lang.VerifyError: (class: kickstartwithbootstrapgrailsplugin/_DemoPage$Suit, method: instanceOf signature: (Ljava/lang/Class;)Z) Incompatible object argument for function call

```
at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:97)

at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)

at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1076)

at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)

at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:906)

at groovy.lang.Closure.call(Closure.java:415)

at groovy.lang.Closure.call(Closure.java:428)

at org.codehaus.groovy.grails.web.pages.GroovyPage.evaluate(GroovyPage.java:283)

... 197 more
```

Caused by: java.lang.VerifyError: (class: kickstartwithbootstrapgrailsplugin/_DemoPage$Suit, method: instanceOf signature: (Ljava/lang/Class;)Z) Incompatible object argument for function call

```
at java.lang.Class.forName0(Native Method)

at java.lang.Class.forName(Class.java:264)

at org.codehaus.groovy.runtime.callsite.CallSiteArray$1.run(CallSiteArray.java:65)

at org.codehaus.groovy.runtime.callsite.CallSiteArray$1.run(CallSiteArray.java:62)

at java.security.AccessController.doPrivileged(Native Method)

at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallStaticSite(CallSiteArray.java:62)

at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallSite(CallSiteArray.java:159)

at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)

at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)

at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)

at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callSafe(AbstractCallSite.java:75)

at F__Develop_Grails_Magic_grails_app_views__DemoPage__form_gsp$_run_closure123.doCall(_form.gsp:136)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:601)

at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)

... 204 more
```
